name: coderiver
description: 河码Flutter版本

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2
  fluttertoast: 2.0.9
  json_annotation: ^2.0.0
  flutter_redux: ^0.5.2
  connectivity: ^0.3.1
  flutter_webview_plugin: ^0.2.1+2
  dio: ^1.0.6
  flutter_localizations:
    sdk: flutter
  event_bus:  ^1.0.1
  flutter_cache_manager: ^0.2.0+1
dev_dependencies:
  build_runner: ^1.1.1
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - images/logo.png
      - images/github_icon.png
      - images/silan_icon.png
      - images/wechat_icon.png
      - images/splash_logo.png
